 task redirect_to_home: :environment do |t, args|

  @site = Site.find(2)

  existing_redirects = []
  redirects = []

  urls  = ['/cupom-de-desconto-absurda',
  '/cupom-de-desconto-abuze',
  '/cupom-de-desconto-acampivale',
  '/cupom-de-desconto-acessorios-para-meninas',
  '/cupom-de-desconto-acquaparadise',
  '/cupom-de-desconto-adega-curitibana',
  '/cupom-de-desconto-agataweb',
  '/cupom-de-desconto-aguia-box',
  '/cupom-de-desconto-aikade',
  '/cupom-de-desconto-albrasil',
  '/cupom-de-desconto-all-posters',
  '/cupom-de-desconto-allianz-assistance',
  '/cupom-de-desconto-ambiance-bijoux',
  '/cupom-de-desconto-ancona',
  '/cupom-de-desconto-andaraki',
  '/cupom-de-desconto-anima-hotel',
  '/cupom-de-desconto-anita-online',
  '/cupom-de-desconto-arco-e-flecha',
  '/cupom-de-desconto-aremo',
  '/cupom-de-desconto-art-em-miniatura',
  '/cupom-de-desconto-atrapalo',
  '/cupom-de-desconto-aura-prata',
  '/cupom-de-desconto-az-perfumes',
  '/cupom-de-desconto-azul-music',
  '/cupom-de-desconto-babbel',
  '/cupom-de-desconto-babyou',
  '/cupom-de-desconto-bagaggio',
  '/cupom-de-desconto-bazar-185',
  '/cupom-de-desconto-bazar-horizonte',
  '/cupom-de-desconto-beate-uhse',
  '/cupom-de-desconto-beate-uhse',
  '/cupom-de-desconto-beatriz-producoes',
  '/cupom-de-desconto-begonia-flores',
  '/cupom-de-desconto-beleza-store',
  '/cupom-de-desconto-bem-me-quer-flores',
  '/cupom-de-desconto-best-foto',
  '/cupom-de-desconto-bibi-calcados',
  '/cupom-de-desconto-bideia',
  '/cupom-de-desconto-billbox',
  '/cupom-de-desconto-biopoint',
  '/cupom-de-desconto-bitcao',
  '/cupom-de-desconto-brinquedos-laura',
  '/cupom-de-desconto-bruna-tessaro',
  '/cupom-de-desconto-calcado-online',
  '/cupom-de-desconto-calcados-online',
  '/cupom-de-desconto-casa-do-capacete',
  '/cupom-de-desconto-cazulo',
  '/cupom-de-desconto-central-fit',
  '/cupom-de-desconto-cherrie-cosmetics',
  '/cupom-de-desconto-cia-do-software',
  '/cupom-de-desconto-cia-dos-livros',
  '/cupom-de-desconto-click-on',
  '/cupom-de-desconto-coritiba-store',
  '/cupom-de-desconto-dabee',
  '/cupom-de-desconto-dadalto',
  '/cupom-de-desconto-dia-filme',
  '/cupom-de-desconto-distinia',
  '/cupom-de-desconto-diversifique',
  '/cupom-de-desconto-doce-beleza',
  '/cupom-de-desconto-dumont',
  '/cupom-de-desconto-ecid',
  '/cupom-de-desconto-ecomtudo',
  '/cupom-de-desconto-edestinos',
  '/cupom-de-desconto-eisenbahn',
  '/cupom-de-desconto-elamais',
  '/cupom-de-desconto-element',
  '/cupom-de-desconto-eletro-angeloni',
  '/cupom-de-desconto-eletrosom',
  '/cupom-de-desconto-ella-store',
  '/cupom-de-desconto-embarque-nessa',
  '/cupom-de-desconto-emporio-body-store',
  '/cupom-de-desconto-encontre-sua-viagem',
  '/cupom-de-desconto-ergosum',
  '/cupom-de-desconto-erozkosz',
  '/cupom-de-desconto-erozkosz',
  '/cupom-de-desconto-estante-virtual',
  '/cupom-de-desconto-extreme-bike',
  '/cupom-de-desconto-falcao-da-informatica',
  '/cupom-de-desconto-fashion-buy',
  '/cupom-de-desconto-feromony-pl',
  '/cupom-de-desconto-feromony-pl',
  '/cupom-de-desconto-fgtec',
  '/cupom-de-desconto-fisiostore',
  '/cupom-de-desconto-flores-dora',
  '/cupom-de-desconto-flores-ontestlin',
  '/cupom-de-desconto-flower-gallery',
  '/cupom-de-desconto-fogo-mix',
  '/cupom-de-desconto-francis-joias',
  '/cupom-de-desconto-francisca-joias',
  '/cupom-de-desconto-galeria-77',
  '/cupom-de-desconto-ganish',
  '/cupom-de-desconto-geral-shopping',
  '/cupom-de-desconto-gigante-da-colina',
  '/cupom-de-desconto-hardbox',
  '/cupom-de-desconto-hardplus',
  '/cupom-de-desconto-havan',
  '/cupom-de-desconto-heavy-metal-rock',
  '/cupom-de-desconto-hering',
  '/cupom-de-desconto-hostelbookers',
  '/cupom-de-desconto-i9-store',
  '/cupom-de-desconto-iba',
  '/cupom-de-desconto-ilentes',
  '/cupom-de-desconto-importe-net',
  '/cupom-de-desconto-informatica-e-cia',
  '/cupom-de-desconto-intymna-kod-rabatowy',
  '/cupom-de-desconto-inusual',
  '/cupom-de-desconto-juff',
  '/cupom-de-desconto-juv-you',
  '/cupom-de-desconto-kamisetas',
  '/cupom-de-desconto-kanstar',
  '/cupom-de-desconto-le-diamonds',
  '/cupom-de-desconto-lefrance',
  '/cupom-de-desconto-lema-21',
  '/cupom-de-desconto-logovia',
  '/cupom-de-desconto-loja-virus',
  '/cupom-de-desconto-lojas-mm',
  '/cupom-de-desconto-lojix',
  '/cupom-de-desconto-lorem-ipsum',
  '/cupom-de-desconto-mala-pronta',
  '/cupom-de-desconto-manga-longa',
  '/cupom-de-desconto-maquina-de-camisa',
  '/cupom-de-desconto-martins-fontes',
  '/cupom-de-desconto-max-viage',
  '/cupom-de-desconto-mega-formiga',
  '/cupom-de-desconto-men-s-market',
  '/cupom-de-desconto-mercure',
  '/cupom-de-desconto-mestre-dos-concursos',
  '/cupom-de-desconto-mundo-do-futebol',
  '/cupom-de-desconto-mundo-positivo',
  '/cupom-de-desconto-my-shoes',
  '/cupom-de-desconto-netmovies',
  '/cupom-de-desconto-nicephotos',
  '/cupom-de-desconto-nova-flor',
  '/cupom-de-desconto-oculos-world',
  '/cupom-de-desconto-oscar-calcados',
  '/cupom-de-desconto-partiu-viagens',
  '/cupom-de-desconto-petite-box',
  '/cupom-de-desconto-ploft-kids',
  '/cupom-de-desconto-produto-direto',
  '/cupom-de-desconto-punkshop',
  '/cupom-de-desconto-revista-caras',
  '/cupom-de-desconto-revista-contigo',
  '/cupom-de-desconto-revista-veja',
  '/cupom-de-desconto-roux',
  '/cupom-de-desconto-rumbo',
  '/cupom-de-desconto-safari-shop',
  '/cupom-de-desconto-sandro-moscoloni',
  '/cupom-de-desconto-selo-reserva',
  '/cupom-de-desconto-seu-enxoval',
  '/cupom-de-desconto-shop-do-esporte',
  '/cupom-de-desconto-shop-express',
  '/cupom-de-desconto-so-futebol',
  '/cupom-de-desconto-sommer',
  '/cupom-de-desconto-studio-som-joao',
  '/cupom-de-desconto-super-games',
  '/cupom-de-desconto-taco',
  '/cupom-de-desconto-terra-do-esporte',
  '/cupom-de-desconto-the-time-store',
  '/cupom-de-desconto-tico-tica-bum',
  '/cupom-de-desconto-todo-livro',
  '/cupom-de-desconto-toymagazine',
  '/cupom-de-desconto-tufi-duek',
  '/cupom-de-desconto-universidade-do-ingles',
  '/cupom-de-desconto-use-huck',
  '/cupom-de-desconto-versia',
  '/cupom-de-desconto-via-calcados',
  '/cupom-de-desconto-vinitude',
  '/cupom-de-desconto-vitrinepix',
  '/cupom-desconto/comida-e-servico-de-entrega',
  '/cupom-desconto/dla-doroslych',
  '/cupom-desconto/outros',
  '/desco',
  '/desconto-fabrica-9',
  '/descontos',
  '/ofertas/americanas-brinquedos',
  '/ofertas/americanas-celulares',
  '/ofertas/americanas-livros',
  '/ofertas/cartao-magazine-luiza',
  '/ofertas/cartao-walmart',
  '/ofertas/casas-bahia-celular',
  '/ofertas/casas-bahia-eletrodomesticos',
  '/ofertas/casas-bahia-moveis',
  '/ofertas/centauro-calcados',
  '/ofertas/centauro-esportes',
  '/ofertas/dafiti-bolsas',
  '/ofertas/dafiti-botas',
  '/ofertas/dafiti-calcados',
  '/ofertas/dafiti-premium',
  '/ofertas/dafiti-sapatilhas',
  '/ofertas/dafiti-vestidos',
  '/ofertas/dia-das-maes',
  '/ofertas/extra-cartao',
  '/ofertas/extra-celulares',
  '/ofertas/extra-delivery',
  '/ofertas/extra-eletrodomesticos',
  '/ofertas/extra-eletronicos',
  '/ofertas/extra-informatica',
  '/ofertas/extra-lista-de-casamento',
  '/ofertas/extra-livros',
  '/ofertas/extra-moveis',
  '/ofertas/extra-notebook',
  '/ofertas/extra-pneus',
  '/ofertas/extra-tablet',
  '/ofertas/extra-tv',
  '/ofertas/extra-xbox-360',
  '/ofertas/kanui-tenis',
  '/ofertas/magazine-luiza-brinquedos',
  '/ofertas/magazine-luiza-celulares',
  '/ofertas/magazine-luiza-lista-de-casamento',
  '/ofertas/magazine-luiza-moveis',
  '/ofertas/magazine-luiza-notebook',
  '/ofertas/magazine-luiza-tablet',
  '/ofertas/melhores-tablets-com-descontos',
  '/ofertas/menores-precos-de-ar-condicionado-e-ventiladores-lojas-ricardo-eletro',
  '/ofertas/netshoes-adidas',
  '/ofertas/netshoes-bicicletas',
  '/ofertas/netshoes-bones',
  '/ofertas/netshoes-calcados',
  '/ofertas/netshoes-camisas',
  '/ofertas/netshoes-chuteiras',
  '/ofertas/netshoes-mochilas',
  '/ofertas/netshoes-nike',
  '/ofertas/netshoes-suplementos',
  '/ofertas/netshoes-tenis',
  '/ofertas/ponto-frio-ar-condicionado',
  '/ofertas/ponto-frio-atacado',
  '/ofertas/ponto-frio-cartao',
  '/ofertas/ponto-frio-celulares',
  '/ofertas/ponto-frio-geladeira',
  '/ofertas/ponto-frio-lista-de-casamento',
  '/ofertas/ponto-frio-livros',
  '/ofertas/ponto-frio-microondas',
  '/ofertas/ponto-frio-moveis',
  '/ofertas/ponto-frio-tablet',
  '/ofertas/ponto-frio-tv',
  '/ofertas/porto-seguro',
  '/ofertas/ricardo-eletro-celulares',
  '/ofertas/ricardo-eletro-celulares?page=2&shop_slug=ricardo-eletro',
  '/ofertas/ricardo-eletro-moveis',
  '/ofertas/ricardo-eletro-notebooks',
  '/ofertas/walmart-celulares',
  '/ofertas/walmart-notebooks',
  '/promocao',
  '/promocao-bebes-criancas-e-brinquedos.html',
  '/promocao-beleza-saude-e-bem-estar.html',
  '/promocao-carro-e-moto.html',
  '/promocao-escritorio-e-escola.html',
  '/promocao-livros-musicas-e-filmes.html',
  '/promocao-presentes-e-flores.html',
  '/promocao-roupas.html',
  '/promocao-software-e-internet.html',
  '/promocao-viagem-ferias-e-eventos.html']

  urls.each do |r|
    query = RedirectRule.includes(:request_environment_rules)
      .where(request_environment_rules: { environment_key_name: 'SERVER_NAME', environment_value: @site.hostname })
      .where(active: true)
      .where(source: r)

    if query.present?
      existing_redirects << query
      next
    end

    rule = RedirectRule.new(
      site_id: @site.id,
      source: r,
      destination: '/',
      active: 1,
      request_environment_rules:
      [RequestEnvironmentRule.new(environment_key_name: 'SERVER_NAME',environment_value: @site.hostname)]
    );

    redirects << rule
  end

  binding.pry

end
