version: '3'
services:
  web:
    volumes:
      - app-source:/usr/src/app
    depends_on:
      - db
      - redis
  worker:
    volumes:
      - app-source:/usr/src/app
    depends_on:
      - web
volumes:
  app-source:
    external: true
